apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'com.kairo.subscriptionwidget'
version = '0.0.0'

android {
  namespace 'expo.modules.kairosubscriptionwidget'
  compileSdk rootProject.ext.compileSdkVersion
  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
